version: "3"

services:
  translatego:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_PORT=5001
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MONGO_URI=${MONGO_URI}
      # The following API keys will be provided by the .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env.production
    volumes:
      - .:/app
    restart: always

